name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.USERNAME }}
        # Remote port
        REMOTE_PORT: ${{ secrets.PORT }}
        # Target directory
        TARGET: ${{ secrets.FOLDER_TARGET }}
