name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: hengkx/ssh-deploy@v1.0.1
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PORT: ${{ secrets.PORT }}
        SOURCE: '/'
        TARGET: ${{ secrets.FOLDER_TARGET }}
        AFTER_COMMAND: 'npm run stop && npm install --production && npm run start'
